import * as pdfjsLib from 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';
const canvas=document.querySelector('#canvas'),flip=document.querySelector('#flipCanvas'),book=document.querySelector('#book'),input=document.querySelector('#page'),count=document.querySelector('#count'),loading=document.querySelector('#loading');let pdf,page=1,busy=false,queued=null;
document.querySelector('#title').textContent=window.CATALOG_TITLE||'Catalog Hùng Pin';document.title=window.CATALOG_TITLE||'Catalog Hùng Pin';
function scaleFor(base){const w=Math.min(innerWidth-(innerWidth<700?20:150),1100),h=Math.max(260,innerHeight-(innerWidth<700?140:160));return Math.min(w/base.width,h/base.height,2)}
async function draw(target,n){const p=await pdf.getPage(n),base=p.getViewport({scale:1}),viewport=p.getViewport({scale:scaleFor(base)*devicePixelRatio});target.width=viewport.width;target.height=viewport.height;target.style.width=viewport.width/devicePixelRatio+'px';target.style.height=viewport.height/devicePixelRatio+'px';await p.render({canvasContext:target.getContext('2d'),viewport}).promise}
function copy(){flip.width=canvas.width;flip.height=canvas.height;flip.style.width=canvas.style.width;flip.style.height=canvas.style.height;flip.getContext('2d').drawImage(canvas,0,0)}
async function go(n){n=Math.max(1,Math.min(pdf.numPages,n));if(n===page)return;if(busy){queued=n;return}busy=true;copy();await draw(canvas,n);book.className='book '+(n>page?'next':'prev');await new Promise(r=>setTimeout(r,680));book.className='book';page=n;input.value=n;busy=false;if(queued){const q=queued;queued=null;go(q)}}
document.querySelector('#prev').onclick=()=>go(page-1);document.querySelector('#next').onclick=()=>go(page+1);input.onchange=()=>go(+input.value);document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(page+1);if(e.key==='ArrowLeft')go(page-1)});let x=0;book.ontouchstart=e=>x=e.touches[0].clientX;book.ontouchend=e=>{const d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45)go(page+(d<0?1:-1))};document.querySelector('#share').onclick=async()=>{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);alert('Đã sao chép đường link')}};
try{pdf=await pdfjsLib.getDocument('catalog.pdf').promise;count.textContent=pdf.numPages;input.max=pdf.numPages;await draw(canvas,1);loading.classList.add('hidden')}catch(e){loading.textContent='Chưa có catalog.pdf hoặc file PDF không mở được.'}
